stages:
  classification_models:
    cmd: cmd=cd olympicskedro && python -m kedro run --pipeline=classification
    deps:
    - olympicskedro/src/olympicskedro/pipelines/classification/nodes.py
    outs:
    - olympicskedro/data/07_model_output
    metrics:
    - olympicskedro/data/08_reporting/classification_metrics.json
