stages:
  classification_models:
    cmd: python -m kedro run --pipeline=classification
    deps:
      - src/olympicskedro/pipelines/classification/nodes.py
      - data/02_intermediate/summer_with_medal_flag.parquet
    outs:
      - data/06_models/classification/
    metrics:
      - data/08_reporting/classification_metrics_flat.json


  regression_models:
    cmd: python -m kedro run --pipeline=regression
    deps:
      - src/olympicskedro/pipelines/regression/nodes.py
      - data/02_intermediate/summer_with_medal_flag.parquet
    outs:
      - data/06_models/regression/
    metrics:
      - data/08_reporting/regression_metrics_flat.json

